library(RMariaDB)# Install and then load the package RMariDB
user <- 'DevUser' #This is the username of user in MYSQL
localuserpassword <- "Dev@User" #This is the Password of user in MYSQL
#this is for establishing connection between Mysql and R
con <- dbConnect(RMariaDB::MariaDB(), user=user, password=localuserpassword, dbname='airbnb_fall', host='localhost')
#below commands are for fetching the data from csv to R
#fileloaction has to be replaced with the location of the file from your system
price <- fread("filelocation/price.csv")
bedtype <- fread("filelocation/bedtype.csv")
cancellationpolicy <- fread("filelocation/cancellationpolicy.csv")
city <- fread("filelocation/city.csv")
country <- fread("filelocation/country.csv")
host <- fread("filelocation/host.csv")
host$host_since<- as.Date(host$host_since,format = "%m/%d/%y")
state <- fread("filelocation/state.csv")
location <- fread("filelocation/location.csv")
propertytype <- fread("filelocation/propertytype.csv")
hostlocation <- fread("filelocation/hostlocation.csv")
neighborhood <- fread("filelocation/neighborhood.csv")
roomtype <- fread("filelocation/roomtype.csv")
property <- fread("filelocation/property.csv")
reviewscore <- fread("filelocation/reviewscore.csv")
listing <- fread("filelocation/listing.csv")
calendar <- fread("filelocation/calendar1.csv")
calendar$available_date<- as.Date(calendar$available_date,format = "%m/%d/%y")
review <- fread("filelocation/review.csv")
review$date<- as.Date(review$date,format = "%m/%d/%y")
reviewscore <- fread("filelocation/reviewscore.csv")
#these commands are to load data from R to MySQL
dbWriteTable(con, "bedtype", bedtype,append=TRUE)
dbWriteTable(con, "cancellationpolicy", cancellationpolicy,append=TRUE)
dbWriteTable(con, "city", city,append=TRUE)
dbWriteTable(con, "country", country,append=TRUE)
dbWriteTable(con, "host", host,append=TRUE)
dbWriteTable(con, "state", state,append=TRUE)
dbWriteTable(con, "location", location,append=TRUE)
dbWriteTable(con, "propertytype", propertytype,append=TRUE)
dbWriteTable(con, "hostlocation", hostlocation,append=TRUE)
dbWriteTable(con, "neighborhood", neighborhood,append=TRUE)
dbWriteTable(con, "roomtype", roomtype,append=TRUE)
dbWriteTable(con, "property", property,append=TRUE)
dbWriteTable(con, "reviewscore", reviewscore,append=TRUE)
dbWriteTable(con, "listing", listing,append=TRUE)
dbWriteTable(con, "price", price,overwrite=TRUE)
dbWriteTable(con, "calendar", calendar,append=TRUE)
dbWriteTable(con, "review", review,append=TRUE)
dbWriteTable(con, "reviewscore", reviewscore,append=TRUE)
